Updates for BGC build
ACCESS-NRI/ACCESS-OM2-BGC pull request #2
Opened 2024-03-19 08:50 UTC by aidanheerdegen

Add changes to covert from ACCESS-OM2 build type to ACCESS-OM2-BGC.

Requires changes to the README and the `spack.yaml` to use `type=ACCESS-OM2-BGC` which was added to the MOM5 spack package (see https://github.com/ACCESS-NRI/spack-packages/pull/72).

2024-03-19 22:09 UTC, CodeGat commented
Whoops, I'll need to update the CI in this repository since it was created before I got CI working.

2024-03-19 22:41 UTC, CodeGat commented
Regarding https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/pull/2/files#diff-e8582e74fa156f4e5729a850e52b24f2fde2d815c2c9c360f88c4cf90db851abL8 (`spack.yaml` Line 8 - `access-om2@git.VERSION`) - would we change the name of the package? I feel that it could clash with the environment names in prerelease/release if the versions are the same (for example, `access-om2-2024_02_1`).

2024-03-19 23:55 UTC, CodeGat commented
So regarding the spack package for access-om2-bgc:
* don't change the spack package name, but hardcode the name of the spack environment to include a `-bgc` (`access-om2-bgc_2024_03_0`). This would mean the environments wouldn't clash, but the packages outside the environment might, if the versions are the same. Needs more testing. 
* add an entry in `spack-packages` for BGC. This wouldn't clash with an environment or package name, but might be nonstandard - do we really want to do a new spack-package for every variant?

2024-03-20 03:37 UTC, aidanheerdegen commented
> * don't change the spack package name, but hardcode the name of the spack environment to include a `-bgc` (`access-om2-bgc_2024_03_0`). This would mean the environments wouldn't clash, but the packages outside the environment might, if the versions are the same.

To be specific, this would require changes to the CD workflow to be able to pass in a spack environment name? As it currently defaults to the spack package in `spack.yaml`:

https://github.com/ACCESS-NRI/ACCESS-OM2/blob/main/.github/workflows/cd.yml#L28


> * add an entry in `spack-packages` for BGC. This wouldn't clash with an environment or package name, but might be nonstandard - do we really want to do a new spack-package for every variant?

No I don't think we do, but this doesn't have to be the last word. Unscrambling this egg wouldn't be too painful: leave deployed model versions as-is and new ones could follow a new approach.

This is part of why being able to [rely on `module load`](https://github.com/payu-org/payu/issues/379) would be nice: it frees us a bit on the implementation detail as we wouldn't need to hard-code paths in model configs, which means we could update how we do it relatively simply and it could be backwards compatible.
 
> @harshula how are variants handled in spack, regarding the package name? If you do a `spack find` would there be something like `access-om2+bgc` for a `bgc` variant?

I can answer: yes. 

```
$ spack find -Lv mom5
-- linux-rocky8-x86_64 / intel@19.0.5.281 -----------------------
uznvr36p3km4qmjvdrxin7nhfyjubmd3 mom5@master~deterministic~optimisation_report build_system=makefile
oucqhr5r4yupkapwb6vsnqh2i6ow4vod mom5@master~deterministic~optimisation_report+repro build_system=makefile
4q2un3c6if5hynashormlklggv55bng5 mom5@master~deterministic~optimisation_report+restart_repro build_system=makefile type=ACCESS-OM
aollz5h3gjqjhb3pkgfkkqqifm75hals mom5@master~deterministic~optimisation_report build_system=makefile type=ACCESS-OM-BGC
4jfyunr427g3rk667hcyir7xrfytlqoo mom5@master~deterministic~optimisation_report build_system=makefile type=MOM_solo
==> 5 installed packages
```

The packages are handled fine, but as you point out environment names would clash. It is possible to store environments in non-default locations. Could we add a prefix (subdirectory) that is the repo name, then any environment created therein is guaranteed to be unique on a per-repository basis only.

2024-03-20 21:37 UTC, CodeGat commented
This branch will need to be rebased onto `main` to get the CI updates

2024-03-20 22:38 UTC, aidanheerdegen commented
!bump major

This is a the first version of a new model so needs a new major (CalVer) version.

2024-03-20 22:42 UTC, aidanheerdegen commented
!bump major

2024-03-21 01:25 UTC, CodeGat requested changes

2024-03-21 01:25 UTC, CodeGat commented on spack.yaml
> +          access-om2: '{name}-bgc/2024.03.0'
Will not require this `-bgc` once the `access-om2-bgc` spack package is created

2024-03-21 01:25 UTC, CodeGat commented on spack.yaml
> +        - 'type=ACCESS-OM-BGC'
Will need to go through the `packages.yaml` syntax to see this syntax - will have to update the CI if this is a possibility (specifically, the `yq` that gets the version - thats why https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/actions/runs/8367053860/job/22908627210?pr=2#step:5:28 is failing)

2024-03-21 22:05 UTC, CodeGat commented on spack.yaml
> +        - 'type=ACCESS-OM-BGC'
Won't be relevant any more, but would still be good to find out - didn't expect that syntax as a possibility!

2024-03-22 04:29 UTC, CodeGat commented
So currently the CI is failing because it hasn't taken into account the possibility that the projections would be anything but `{name}/{version}`. For example, `mom5` has the projection `{name}-bgc/0000.00.00`. This PR should fix that, and we can get a deployment on the way: https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/pull/4

2024-03-22 09:18 UTC, aidanheerdegen commented
Deployment is failing because the environment still specifies `nci-openmpi` which we've removed from `spack-config`

https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/pull/2/files#diff-e8582e74fa156f4e5729a850e52b24f2fde2d815c2c9c360f88c4cf90db851abL24-L25

2024-03-27 05:23 UTC, CodeGat approved these changes

2024-03-27 05:32 UTC, merged